### PR TITLE
feat(postgres-with-jwt): create

### PR DESCRIPTION
**Pull request by ivangabriele**

### CODE REVIEW

**Comment by revolunet** [comment]
Nice one thanks !

Do you think this could be useful for our hasura+jwt+pg setup in the sample-app ?

**Comment by ivangabriele** [comment]
> where is this test.sh `test.sh` used ?

Removed ✔️

**Comment by douglasduteil** [comment]
@revolunet Still useful ? We merge ? We close ?

**Comment by revolunet** [comment]
can be closed

**Pull request closed without merging**
