### PR TITLE
feat: add nginx-error-pages

### PR DESCRIPTION
**Pull request by revolunet**
this comes from https://gitlab.factory.social.gouv.fr/infra/images-docker/-/blob/master/nginx-error-pages

### CODE REVIEW

**Comment by revolunet** [comment]
this part is interesting : 

```yaml
.change_rules:
  rules:
    - changes:
        - nginx-error-pages/*
```

i can add it to other jobs too

not from [gitlab docs](https://docs.gitlab.com/ee/ci/yaml/#onlychangesexceptchanges) : 

> If there is no Git push event, such as for pipelines with sources other than the three above, changes can’t determine if a given file is new or old, and will always return true.

**Comment by revolunet** [comment]
we'd want to auto-update the image when our maintenance page is updated too

**Comment by douglasduteil** [comment]
> we'd want to auto-update the image when our maintenance page is updated too

Shouldn't we put this code in the https://github.com/SocialGouv/maintenance/ repo then ?

**Comment by douglasduteil** [comment]
@revolunet similar to https://github.com/SocialGouv/docker/pull/169#issuecomment-610008973

**Comment by revolunet** [comment]
i dont think its the same as #169 as its based on nginx ingress image

not sure if the best place is here or at maintenance repo... 🤔  i guess its here as its a docker image and we should use git dependency for renovate ?

**Pull request closed without merging**
